### ISSUE TITLE
Performance Issue in IE10 due to FORM DOM elements

### ISSUE THREAD

**Issue by vinodache** [jonsamwell/angular-auto-validate#103]
Hi Jon
First of all, Thanks for the great utility. It is really great.
I had a query on the line below.

angular.forEach((frmElement[0].all || frmElement[0].elements) || frmElement[0], function (ctrlElement) { 
        processElement(ctrlElement, true, clonedOptions); 
       }); 

For IE10, I find that frmElement[0].all and frmElement[0].elements are both available and frmElement[0].all seems to hold a huge amount of data compared to .elements which might not be relevant for our validation purpose. This seems to impact the performance in IE10. I do not see this issue in IE11 since in IE11 has frmElement[0].all as null.
Had a suggestion, incase there are no impacts and the fact that IE8 support is no longer a mandate, would it be a good idea to change this code to,

angular.forEach((frmElement[0].elements || frmElement[0].all) || frmElement[0], function (ctrlElement) { 
        processElement(ctrlElement, true, clonedOptions); 
       }); 

Once again, thank you so much for your support. 

Cheers

**Comment by jonsamwell** [comment]
Seems like a good idea could you do a PR?

**Comment by jonsamwell** [comment]
Will be fixed in next release
