### ISSUE TITLE
Could you please publish on npm repository ?

### ISSUE THREAD

**Issue by kamalpatel125** [jonsamwell/angular-auto-validate#108]
Hi Jon,

Would it be possible to publish on npm ?  Also, Does it support angular material design ?

Kind Regards,

Kamal.

**Comment by jonsamwell** [comment]
Hey Kamal, I'll sort this out for you now!  I've had a few issues come up with devs using it with angular material design so I think it should.  If not let me know.

**Comment by jonsamwell** [comment]
Sorted! 

https://www.npmjs.com/package/angular-auto-validate

**Comment by kamalpatel125** [comment]
Hi Jon,
Thanks for looking at this and please let me know if I can contribute you anywhere in this.

Appreciate your help !

Thanks

Kamal Patel

**Comment by jonsamwell** [comment]
If you need any more feature for it feel free to add them or let me know.  I really need to update the documentation and plunker examples see https://github.com/jonsamwell/angular-auto-validate/wiki/Getting-Started

**Comment by jonsamwell** [comment]
@kamalpatel125 I think you'll need to do a custom element modifier for material design so once you have done it could you do a pr and commit it back to this repo?
