### ISSUE TITLE
Translation strategy for custom validation messages translated using angular-translate

### ISSUE THREAD

**Issue by dhiraj** [jonsamwell/angular-auto-validate#109]
I've got custom validation error messages that are shown with angular-auto-validate, as per earlier issues #71  and #96 and now I'm implementing translations using the angular-translate in my app.

I need to translate my custom error validation messages, but can't figure out a clear strategy to do the same.

Ideally, I'd like to have my custom error translations load using the normal angular-translate mechanism which is asynchronously loading the translation json file from the server. By the time I arrive at the signup controller where I'm using angular-auto-validate to validate the input form, the angular-translate translation for the current language has already loaded and is available.

If it is possible, I'd like to eliminate the extra round trip that will happen if I call  `setCulture()` on the `defaultErrorMessageResolver` object in the controller, and have *both* my custom messages as well as the included translations from angular-auto-validate included in my own, single, translation strings file that is thus only downloaded once.

Please recommend your thoughts on the best strategy to achieve this, thanks!

**Comment by jonsamwell** [comment]
Hi @dhiraj 

The setCulture method takes in a loading function that you could use to stop the default loading path and construct the object using angular translate.  See

https://github.com/jonsamwell/angular-auto-validate/blob/ac04a5d19b9971de463900a21ee278971bffb2ec/src/services/defaultErrorMessageResolver.js#L72

The code may look something like this:

```javascript
defaultErrorMessageResolver.setCulture('en-gb', function(cultureCode) {
  var defer = $q.defer();
  var validationMessages = {};
  // construct the expected validation object using angular translate
 validationMessages.required = $translate.instant('required');
 // any other messages you need on the object
// see https://github.com/jonsamwell/angular-auto-validate/blob/master/src/lang/jcs-auto-validate_en-GB.json

  defer.resolve(validationMessages);
  return defer.promise;
});

```
