### ISSUE TITLE
async validation with updateOn={'blur'} doesn't work

### ISSUE THREAD

**Issue by anatolibarski** [jonsamwell/angular-auto-validate#112]
Hi, I love the library, but one thing does not work for me:

I use ui-validate-async (just an asynchronous validator) together with angular-auto-validate.

Everything works without updateOn={'blur'}, but when I use it, the validator is executed and rejects the promise, but angular-auto-valdiate resolve function does not get called untill a second blur event (I need to click around for this)

**Comment by jonsamwell** [comment]
Could you do a plunker that reproduces the error and i'll get a fix in.  

Thannks

**Comment by anatolibarski** [comment]
I will but too busy at the moment, may be the problem is even easier to reproduce: 

when I use

$scope.form.modelName.$setValidity('key', false),

I will not see the validation error first. I need to click around first.

**Comment by jonsamwell** [comment]
updateOn={'blur'} is invalid it should be updateOn='blur' see https://docs.angularjs.org/api/ng/directive/ngModelOptions.

**Comment by jonsamwell** [comment]
This seems to work OK (async validator with update on blur)

http://plnkr.co/edit/nYX48wdfdN78C1EJH73s?p=preview

**Comment by jonsamwell** [comment]
I think I've fixed it!!!
Try getting v1.19.3
