### ISSUE TITLE
Validation Summary/Backend validation

### ISSUE THREAD

**Issue by anatolibarski** [jonsamwell/angular-auto-validate#113]
Hi I would like to propagate Backend Error to a Frontend Validation Error. For a specific input control with ng-model, using $setValidity('key', false); $setDirty(); works.

But if I cannot match an error to a specific control, with angular I am able to use $setValidity with the form instead of ng-model. But those errors are not displayed by angular-auto-validate?

Do you have a solution for this use-case? I think it's pretty basic need.

Thank You!

**Comment by jonsamwell** [comment]
Hi @anatolibarski,

Yes you can use setExternalValidationError on the ngModel controller. See

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/config/ngModelDecorator.js#L61

There isn't any documentation for this yet but I will get around to it one day.

Jon

**Comment by jonsamwell** [comment]
You can also see the tests here

https://github.com/jonsamwell/angular-auto-validate/blob/master/tests/config/ngModelDecorator.spec.js#L162
