### ISSUE TITLE
some input no validation,why validate?

### ISSUE THREAD

**Issue by TNT-Likely** [jonsamwell/angular-auto-validate#115]
some input no validation,why validate?

wish someone can help me ,thanks

**Comment by jonsamwell** [comment]
Sorry I have no clue what you mean please provide a plunker

**Comment by TNT-Likely** [comment]
![qq 20151125165241](https://cloud.githubusercontent.com/assets/9278923/11392474/fcdb2872-9394-11e5-8602-7310465b648b.png)

**Comment by jonsamwell** [comment]
Please do a reproducing plunker.

**Comment by jonsamwell** [comment]
This seems ok to me

http://plnkr.co/edit/BY57X2C7O0OQs0VO3956?p=preview

See the Nickname field.  It does not have a required attribute on it and is validated OK.  If you mean you don't want it to be validated at all unless it has some text in it the library cannot do that.  You would need to create a custom dom modifier to determine this.  Or you could mark the field with the disable-valid-styling="true". See:

http://jonsamwell.github.io/angular-auto-validate/#enabl-disable-styling

Working plunker here:

http://plnkr.co/edit/1rVHjFekwPEikyc0FF9g?p=preview

**Comment by TNT-Likely** [comment]
thanks,maybe some other plugins was wrong.

**Comment by jonsamwell** [comment]
No worries :-)
