### ISSUE TITLE
Focus first invalid field on submit

### ISSUE THREAD

**Issue by jgesser** [jonsamwell/angular-auto-validate#118]
It would be nice if we could set an option, in one specific form or globally, to make the first invalid input focused when the form is submitted.

BTW: This project is awesome. It is helping me a lot. Congratulations for the great job you are doing here.

**Comment by jonsamwell** [comment]
Thanks for your feedback and sorry for the delay in responding.  Focusing the first invalid input could be done with a custom dom modifier (see http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers) so I doubt I'll put this into the core library.  Although it you fancy doing a pull request that would be great!

Have a good new year!

Jon
