### ISSUE TITLE
Unable to run auto-validate

### ISSUE THREAD

**Issue by deepakmani** [jonsamwell/angular-auto-validate#121]
Hi Sir,

Thanks for your module.
 I created a form like this in my HTML:

````
<form name="signupFrm" novalidate="novalidate">
    <div class="form-row">
        <label>Username:</label>
        <input name="username"
            ng-model="model.username"
            ng-minlength="3"
            ng-maxlength="10"
            required/>
    </div>
    <div class="form-row">
        <label>Password:</label>
        <input name="password"
            type="password"
            ng-model="model.password"
            ng-minlength="3"
            ng-maxlength="10"
            required/>
    </div>
</form>
````

when I enter data into the form I get this message in the console:
Angular-auto-validate: invalid bs3 form structure elements must be wrapped by a form-group 

Can you suggest where to look into? Also is there a way to run validation when the form is loaded itself?

Thanks,
Deepak

**Comment by jonsamwell** [comment]
Hi Deepak,

You will need an ng-submit attribute on the form.  By default the module uses a bootstrap 3 element modifier.  An element modifier is responsible for visually altering an element depending on it validation state.  For example when it is valid it would have a green border etc.  Therefore, it you are using bootstrap 3 you will need to either adhere to bootstrap's  convention of form layout (see http://getbootstrap.com/css/#forms-example) or create a custom element modifier that is able to set the visual state of an element for you application's particular html structure (see http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers).

See a working bootstrap 3 plunker here http://plnkr.co/edit/R4vGhrSYvKJREMV7Q4rC?p=preview

I hope this helps.

Jon

**Comment by deepakmani** [comment]
Thank you for the detailed reply Jon! After  using form-group and
form-control it is working like a charm! I didn't need a button of type
submit or ng-submit.
I had taken the html from your github page, perhaps you can update that bit.

Also, is there a way to run validation as soon as the form loads, so that I
can see errors of a pre-loaded form.

Thank you,
Deepak
