### ISSUE TITLE
Validation is failing intermittently

### ISSUE THREAD

**Issue by go4varuntyagi** [jonsamwell/angular-auto-validate#128]
On my page validation is failing intermittently. I have found that **"frmCtrl.autoValidateFormOptions.disabled**" is getting true sometimes due to which validation process is not getting triggered.

Found this condition in source file.

                        if (frmElement === undefined || (frmCtrl !== undefined && frmCtrl.autoValidateFormOptions.disabled)) {
                            return frmElement !== undefined;
                        }

Could someone help

**Comment by jonsamwell** [comment]
Could you do a reproducing plunker so I have something to debug?

**Comment by jonsamwell** [comment]
Not really sure how to progress this as I have not seen this behaviour or can reproduce it.  Waiting for a plunker that reproduces it....

**Comment by jonsamwell** [comment]
Closing as no reproducing plunker provided so no way to debug.  Feel free to re-open when one is provided
