### ISSUE TITLE
Validation is failing when page reloads

### ISSUE THREAD

**Issue by bhavesh-vyas** [jonsamwell/angular-auto-validate#129]
Everything working fine, until user reloads the browser page..
I am unable to figure out why.

if we logout and then login form validation also doesn't work,
But if we reload here (on Login page) then it starts working again

But when the page is reloaded inside the dashboard it fails again...

I have just added the dependency in module and simply using required validation in html. nothing more is added.

**Comment by jonsamwell** [comment]
Could you do a reproducing plunker.  I am using this on lots of sites and never seen this behaviour.

**Comment by jlengwork** [comment]
Recommend this issue be closed.  The issue is not actually with angular-auto-validate, but with ocLazyLoad wiping out the decorators when modules are lazyloaded on a page refresh.
