### ISSUE TITLE
Tests fail with Angular 1.5.0 release

### ISSUE THREAD

**Issue by jpmckearin** [jonsamwell/angular-auto-validate#130]
If I change the angular and angular-mocks dependencies to 1.4.9 everything runs fine.

**Comment by jonsamwell** [comment]
What fails and why.  Feel free to submit a PR to fix the issue(s)

**Comment by jpmckearin** [comment]
Sorry for being vague about this. Seems to be a compatibility issue between angular 1.5.0 and PhantomJs 1.x. I will attempt to implement a fix and submit a pr.
