### ISSUE TITLE
Error with extending native String object with format method

### ISSUE THREAD

**Issue by jpmckearin** [jonsamwell/angular-auto-validate#132]
In defaultErrorMessageResolver.js, line 5, we extend the native String object to have a format function. On line 7, we reference this.replace. For some reason, I am suddenly getting an error that "this" is undefined. I'm not sure what change might have caused this...

```
4  if (!('format' in String.prototype)) {
5    String.prototype.format = function () {
6      var args = arguments;
7      return this.replace(/{(\d+)}/g, function (match, number) {
8        return typeof args[number] !== undefined ? args[number] : match;
9      });
10  };
11 }
```

![image](https://cloud.githubusercontent.com/assets/6679168/13656478/f0949748-e62c-11e5-9b53-b16dd5a2ec7f.png)

**Comment by jpmckearin** [comment]
I know it's a matter of opinion, but shouldn't we just use a generic "formatString" function or similar instead of extending a native object? I understand it would remove some syntactic sugar, but would resolve issues such as this. Also, "format" is only used 4 times - all in the same file (defaultMessageErrorResolver.js.) If there is support for this, I don't mind submitting a pr.

**Comment by jonsamwell** [comment]
Sure - I think in this case I would agree with you feel free to submit a PR to fix this.
