### ISSUE TITLE
Bootstrap validation icon position for dropdown

### ISSUE THREAD

**Issue by bravenewworlds** [jonsamwell/angular-auto-validate#134]
Bootstrap validation icon for dropdown appears in the wrong position in Forefox and Chrome. In IE11 everything is fine.

![Image](http://oi64.tinypic.com/286qvdj.jpg)

You can see the [Plunker](http://plnkr.co/edit/NgdTP0NC12CqubHzz9gC?p=preview)

**Comment by arung86** [comment]
you can add a simple class to adjust the right positioning , 
```
select + span.glyphicon.glyphicon-ok.form-control-feedback {
    right: 5px;
}
```
Bootstrap documentation says, 
> Icons, labels, and input groups
Manual positioning of feedback icons is required for inputs without a label and for input groups with an add-on on the right. 

so hope this helps, the above solution works fine with IE also.
