### ISSUE TITLE
the use of forceValidation

### ISSUE THREAD

**Issue by maoting** [jonsamwell/angular-auto-validate#136]
$scope.$watch('vm.model.name', function() {
          $scope.vm.model.email = $scope.vm.model.name
})

When the error message is "This field is required", I set the value of email as above, but the message don't disappear.

In the "jcs-auto-validate.js" , I update "opts.forceValidation = true;", the message can disappear.

Can you explain for me the use of  "forceValidation"?

Thank you very much!

**Comment by jonsamwell** [comment]
It is used to the the validation even if the form or element is valid
