### ISSUE TITLE
Collect all error messages within a form

### ISSUE THREAD

**Issue by RaviKaruturi** [jonsamwell/angular-auto-validate#142]
We have nested forms and within a sub-form there are many input fields. Displaying inline error messages for all these input fields does not look nice in our case. So, we are thinking of displaying all error-messages at the top of the sub-form. 
So,currently, is there a way to collect all of the error messages for a specific form?

**Comment by jonsamwell** [comment]
Yeah you'd have to do a custom dom modifier to put all the element error messages in some common place

See http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers
