### ISSUE TITLE
Bootstrap3ElementModifier incorrectly always injecting styles into document

### ISSUE THREAD

**Issue by Skinner927** [jonsamwell/angular-auto-validate#143]
On line https://github.com/jonsamwell/angular-auto-validate/blob/0b2d4b691ba978aa556a7ad2ed1c5fa9f2e901ce/src/services/bootstrap3ElementModifier.js#L31

The styles for animated icons are always injected even if you're not using bootstrap3ElementModifier.

Additionally, https://github.com/jonsamwell/angular-auto-validate/blob/0b2d4b691ba978aa556a7ad2ed1c5fa9f2e901ce/src/services/bootstrap3ElementModifier.js#L134

Is missing the closing `>` on the `</span>`.

I've also created a very basic bootstrap 4 element modifier. I plan on creating a PR possibly this weekend and will fix the above. Just wanted to put this out there before hand so the PR isn't a complete shock.

**Comment by jonsamwell** [comment]
Thanks and sorted!  Any news on the BS4 modifier?
