### ISSUE TITLE
ng-pattern not working 

### ISSUE THREAD

**Issue by anhuisunfei** [jonsamwell/angular-auto-validate#144]
``` html
  <input type="number" 
                        	required 
                        	ng-pattern="/^\-?\d+$/"
                        	class="form-control">
```

**Comment by jonsamwell** [comment]
No ng-model

**Comment by anhuisunfei** [comment]
I want add customer error message!

**Comment by jonsamwell** [comment]
Please read the documentation!

https://github.com/jonsamwell/angular-auto-validate/wiki/Custom-Validators-and-Error-Message

http://jonsamwell.github.io/angular-auto-validate/#overriding_error_message

**Comment by anhuisunfei** [comment]
tanks!
