### ISSUE TITLE
Can't validate on nested component forms

### ISSUE THREAD

**Issue by parker789** [jonsamwell/angular-auto-validate#147]
Hey Jonsamwell,

I've been reading through issues for the past couple hours, and am finally at a loss.  In my application I use the new angular `.component()` to re-use code, some of which happen to be form components.  In most, if not all, these scenarios, the `<form>` is not within the component's template itself, but in the parent view where the component is instantiated:

```
<form>
  <my-component></my-component>
</form>
```

I am trying to use angular-auto-validate to display error messages within fields **inside** the component templates.. and I thought I solved the issue when I came across `register-custom-form-control`; this worked in parsing the `$error` on a field where I use a custom directive (angular-ui-select) and correctly displaying the error message.  Now, I have almost the same scenario, except this time I'm just trying to validate a native HTML `<select required></select>`.  The form correctly updates the `$error` object, but angular-auto-validate will not pick up this error to display a message. 

Please give me some insight! Thanks :)

Edit: fixed formatting issues

**Comment by jonsamwell** [comment]
Could you do me a basic plunker example and I will take a look today.
Thanks!

**Comment by parker789** [comment]
Well thank you! As I'm putting together a plunkr I realize'd the issue.. had a rogue `ng-submit-force="true"` still in my code from a demoable version.  Seems that everything was working all along. Will close this. :)

**Comment by samagit** [comment]
Hi Parker,
Could you share your example to show me how did you resolve it?
Thanks

**Comment by parker789** [comment]
@samagit 

Hey there,

Sorry for such a long delay; I hope you're not still stuck with this!  It actually ended up not being an issue with auto-validate.  I had `ng-submit-force="true"` still in my parent component's `<form>`, so none of my error validation was being checked. I pulled that out and everything worked flawlessly.

Hope it helps!
