### ISSUE TITLE
how to avoid the error 'invalid bs3 form structure elements' in a non-validation form

### ISSUE THREAD

**Issue by flyingdew** [jonsamwell/angular-auto-validate#149]
I use bs3.
when I change the elements of a form that I don't want to validate,it always throws
'invalid bs3 form structure elements must be wrapped by a form-group class',
I want to know how to avoid this.

**Comment by jonsamwell** [comment]
You must have an invalid BS3 form structure.  The BS3 element modifier is expecting form elements to be wrapped in a form-group class.  If you don't want to do this you'll have to create your own element modifier or copy the BS3 one and remove the code that checks the form is a valid bs3 structure.

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/services/bootstrap3ElementModifier.js

**Comment by flyingdew** [comment]
Thanks for your quick response,I'll try it.
