### ISSUE TITLE
Overriding messages

### ISSUE THREAD

**Issue by atxpace** [jonsamwell/angular-auto-validate#15]
Love the work you're doing with this...

I would love to override the 'pattern' message as it's not that user-friendly. I can't expect my users to understand the constraints of a regex! :)

Anyways, I have not been successful doing this as per the docs here. Could you please provide a pointer or a little help getting this working? I assume the custom error message resolver is the way to go? Is this necessary for overriding just 1 message?

**Comment by dustin-page** [comment]
This works for overwriting the error message for an input with 1 type of pattern, but usually my forms have multiple inputs with regex pattern attributes and I would like user-friendly error messages for each of them. Is there any way to get this to work?
Examples:
Phone Number:
Soc Security Number:
Zip Code:
Account Number:
