### ISSUE TITLE
conflict with sb-admin admin template

### ISSUE THREAD

**Issue by criduvero** [jonsamwell/angular-auto-validate#159]
I try to implelemnt in Angular SbAdmin template and it does not work, help me please.
https://github.com/start-angular/sb-admin-angular

It does the submit in $valid=false

**Comment by jonsamwell** [comment]
@criduvero please provide a reproducible plunker so I can debug it.

**Comment by criduvero** [comment]
There must be an error with the template. All works but if I recharge the page, it fails.
