### ISSUE TITLE
Submit should have ability to validate entire form in addition to ng-submit-force

### ISSUE THREAD

**Issue by abobwhite** [jonsamwell/angular-auto-validate#26]
When a user clicks the submit button in a form, the paradigm I am following will present a growl message to the user indicating to correct the form errors, jump to the top-most error, etc. I also need those errors to be indicated. Right now, it appears this module has the ability to do one or the other, not both. Could we add some sort of addition ng-submit-\* option so that the validation still occurs (highlighting all invalid fields and showing error messages) but it also executes the submit method on the controller so that we can execute additional logic?

**Comment by martinib77** [comment]
I'm having the same requirement as @abobwhite, but i wish it could be done as a global event or preference defined on the config part of the directive. A function to be called when the validation fails. That way i can use that logic in several places.
Is that possible ?
