### ISSUE TITLE
Docs say to use setDefaultErrorMessageResolver, but method doesn't exist

### ISSUE THREAD

**Issue by abobwhite** [jonsamwell/angular-auto-validate#29]
The documentation at http://jonsamwell.github.io/angular-auto-validate/ say to use ```setDefaultErrorMessageResolver``` but there is only ```setErrorMessageResolver```

Also, the docs on how to set it are incomplete: ```validator.setDefaultErrorMessageResolver(myCustomErrorMessageResolver)``` should read: ```validator.setErrorMessageResolver(myCustomErrorMessageResolver.resolve)```

**Comment by jonsamwell** [comment]
Sorry for the late reply I'm doing a bit of travelling at the moment and don't have internet very often.  Thanks for finding this I'll update it.

**Comment by jonsamwell** [comment]
Thanks for this - the docs are now updated!
