### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined - version "v1.13.22 - 2014-12-06" 

### ISSUE THREAD

**Issue by StanislavPrusac** [jonsamwell/angular-auto-validate#30]
Hi, thanks for great AngularJS  module!

All work great at version "v1.13.22 - 2014-12-04" but after change at version "v1.13.22 - 2014-12-06" I got error:
TypeError: Cannot read property 'find' of undefined
Line 288 in version "v1.13.22 - 2014-12-06"
```javascript
angular.forEach(el.find('span'), function (spanEl) {
```
My HTML code is:

```HTML
<div class="form-group" >
   <label class="col-sm-2 control-label">Role</label>
	<div class="col-sm-10" >
		<div ng-repeat="name in jsonRoleName" >
			<div class="radio" > 
				<label for="{{name}}" > <input type="radio" ng-model="UserIdentityData.Role" ng-value="name" id="{{name}}" name="favorite" > {{name}} </label>
			</div>
		</div>
	</div>
</div>
```

Thanks.
Stanislav

**Comment by jonsamwell** [comment]
Sorry for the late reply - I'm doing a bit of travelling at the moment and don't have internet access all that often.  Could you do a reproducing plunker?  First guess is the routine that gets the initial 'el' is not returning for your html.  I'll try and look a bit later.

Jon

**Comment by jonsamwell** [comment]
I think I have a fix in for this so could you update to the latest version (v1.15.22 on bower) and check?

Thanks!
