### ISSUE TITLE
ErrorMessageResolver uses non "ng-" prefixed attribute as default and can cause conflict with browser defaults (IE9)

### ISSUE THREAD

**Issue by abobwhite** [jonsamwell/angular-auto-validate#33]
I ran across an issue today where one of my inputs had ```ng-maxlength="100"```. Every time I saw the error message, it would have the value ```2147483647``` instead of ```100```. As it turns out, the code below checks for the attribute matching the errorType by default. maxlength is the browser property that limits the physical amount of characters that can be entered into the field. In IE9, this became a problem because even though I did not physically specify maxlength, the browser defaulted the property. Because of this code, the ```parameter``` was found and it never looked at my ```ng-maxlength``` attribute.

```
parameter = el.attr(errorType);
if (parameter === undefined) {
    parameter = el.attr('data-ng-' + errorType) || el.attr('ng-' + errorType);
}
```

Because this is specifically angular, could we not alter the code to look for ```ng-``` version of the attribute first and have the non-prefixed attribute as a fallback? Such as:

```
parameter = el.attr('ng-' + errorType);
if (parameter === undefined) {
    parameter = el.attr('data-ng-' + errorType) || el.attr(errorType);
}
```

I had already created a custom message resolver for my app for other reasons so I just altered this code in my version, however, I think that this should be a change in the DefaultMessageResolver.

**Comment by jonsamwell** [comment]
This seems like a sensible plan - I'll get the code change in tomorrow.  :-)

**Comment by jonsamwell** [comment]
Sorry for the delay.  Issue fixed in commit 888ecd042affb391e57591a2f18f22395ba1f520 and available on bower V1.15.22

Thanks!!!!

**Comment by abobwhite** [comment]
@jonsamwell Thanks! I appreciate your efforts. Now, if I can just get people to use Ember instead of Angular...

**Comment by jonsamwell** [comment]
Ha, not sure about using Ember!
