### ISSUE TITLE
Suppress Message Flag/Option

### ISSUE THREAD

**Issue by pjwalmsley** [jonsamwell/angular-auto-validate#36]
I want to suppress error messages (but not styling) for select fields and radio buttons in my app to reduce visual clutter.  As far as i'm aware this feature doesn't exist.  

Currently trying to do it with a custom message provider but it feels hacky.  

A config option or property on the respective field would work well.  

I could see others needing this feature as well.  Whats your take on it?

**Comment by jonsamwell** [comment]
I think this is a good idea I would suggest an attribute on the element you don't want the message to appear on 

<input type="text" ng-model="vm.model.name' disable-validation-message="true" />

This should be fairly simple to implement on the validation manager so I'll look at doing this today/tomorrow.

Thanks!

**Comment by pjwalmsley** [comment]
Thank you!  I look forward to pulling down the enhancement!  :)

**Comment by pjwalmsley** [comment]
I may still implement it the other way as well for our purposes.  If so i will let you know.

**Comment by pjwalmsley** [comment]
Also I don't think we would even need to 'pass true'.  We could just check if disable-validation-message is undefined.  

    <input type="text" ng-model="vm.model.name' disable-validation-message/>

    config.validate =  (disableValidationMessage != undefined);

**Comment by jonsamwell** [comment]
Yes we could use it as a default boolean attribute like required is.  I'll get around to this soon.

**Comment by pjwalmsley** [comment]
Sounds good!  Thanks!

**Comment by jonsamwell** [comment]
Fixed in commit 2da11a83e8ecfed2593d9915659f318c7869059f  and a new release up on bower v1.16.22
