### ISSUE TITLE
Not loading en I18n json file.  Instead returning default from cache.

### ISSUE THREAD

**Issue by pjwalmsley** [jonsamwell/angular-auto-validate#37]
In my run function I call setI18nFileRootPath then setCulture.  Theoretically setCulture takes care of loading the culture.  Because en-us/en-gb are hard coded in the js setCulture does not load these from the newly specified error lang file thus fails to resolve custom messages.  

As a temporary fix I have set both undefined.

Glancing at the code it appears setCulture is only ever called by a user.  So it seems the role of this check is solely caching.  Perhaps the best solution would be to keep this method similar to how it is now and rename the default errors lang object and fallback to it where no real cache exists?

**Comment by jonsamwell** [comment]
Yes I see your point here.

I think you could clear the error messages before you call set culture then these default cultures wouldn't be in the cache and it would request them.  Something like:

<pre><code>
angular.autoValidate.errorMessages = {};
defaultErrorMessageResolver.setI18nFileRootPath('../src/lang/');
defaultErrorMessageResolver.setCulture('en-gb');

 defaultErrorMessageResolver.getErrorMessages().then(function (errorMessages) {
      errorMessages['nameRequired'] = 'Please enter your name';
 });
</code></pre>

**Comment by pjwalmsley** [comment]
Yup that worked.  

However, I ended up loading the errors from $translate in a custom error message resolver factory instead. :) Thanks for the responses and great library!

**Comment by leoalmar** [comment]
@jonsamwell you could change the default culture name to "default", like this:

#### angular-auto-validate/src/services/defaultErrorMessageResolver.js

```
// line 17:
from:
angular.autoValidate.errorMessages['en-us'] = angular.autoValidate.errorMessages['en-gb'] = {

to:
angular.autoValidate.errorMessages['default'] = {
```

```
// line 32:
from:
var currentCulture = 'en-gb',

to:
var currentCulture = 'default',
```

Is not necessary to clear the messages, and if you want to use remote messages will work normally.

**Comment by jonsamwell** [comment]
Should be fixed in v.1.19.0 please let me know
