### ISSUE TITLE
Not displaying validation when updateOn is set to 'submit'

### ISSUE THREAD

**Issue by emfor** [jonsamwell/angular-auto-validate#38]
Hi,
I've setup an input with ng-model-options="{updateOn: 'submit'}" but when I click submit no visible signs of validation apperas. Would it be possible to add such a functionlity?

Best regards,
Mateusz

**Comment by jonsamwell** [comment]
Hi Mateusz,

the ng-model-options polyfill I did would not work with updateOn submit as the control does not have such an event which is probably why it is not validating.  Does it validate ok if you set the updateOn to blur?

I wouldn't add such a custom piece of functionality to the library but this could be achieved with a custom element modifier that only made the element valid/invalid when the submit button has been pressed.  You might need another directive on the submit button to tell your custom element modifier that the submit button has been pressed and it can change the visual style of the elements.

http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers

**Comment by emfor** [comment]
Thanks for the answer. Yes everything works great with 'blur'. I'll look into Your suggestions.

Thanks!
