### ISSUE TITLE
Custom Validation Help

### ISSUE THREAD

**Issue by imomin** [jonsamwell/angular-auto-validate#43]
Hi there, I need some help from experts with custom validation. In my case the validation message has a dynamic value. Little background, I have a number field with decimal value. End user can customize it to set whatever precision they want for the decimal. I am planning to use RegEx to validate the value and I must use a directive.  Problem is, after I set the ExternalValidation, its shows the custom message but then it gets replaced with "Please add error message for null". How do I make the original message stick? Or, is there another way to achieve this?

Below is my code for your reference.

		.directive('cfNumber', ['validationManager', '$window',function(validationManager, $window) {
			return {
				restrict: 'A',
				require: 'ngModel',
				priority: 100,
				link: function($scope, iEl, iAttrs, ctrl) {
					$scope.precision = 4;//$scope.input.options.precision;
					var regex = /^\d+(()|(\.\d{1,4})?)$/;
					var validator = function(value){
							if(value.toString().length > 0 && (parseFloat(value) === 'NaN' || !regex.test(parseFloat(value)))){
								ctrl.$valid = false;
								ctrl.$setValidity(null,false);
								ctrl.setExternalValidation(null,"Number must have " + $scope.precision + " decimal places.",false);
								//validationManager.setElementValidationError(iEl, null, "Number must have " + $scope.precision + " decimal places.");
							}
							return $window.parseFloat(value) ? ''+value : value;
						};
					ctrl.$parsers.push(validator);
					ctrl.$formatters.push(validator);
				}
			}
		}])

Another option is to set the error message like following:

defaultErrorMessageResolver.getErrorMessages().then(function(errorMessages) {
			errorMessages['decimalValidation'] = 'Number must have {0} decimal places.';
		});

With below directive, however, I'm not sure how to replace {0} with that value that comes in from the input field &lt;input ng-model="numberField" validate-decimal="4"  type="number"&gt;

.directive('validateDecimal', ['validationManager', '$window',function(validationManager, $window) {
		return {
			restrict: 'A',
			require: 'ngModel',
			priority: 100,
			link: function($scope, iEl, iAttrs, ctrl) {
				$scope.precision = 4;//$scope.input.options.precision;
				var regex = /^\d+(()|(\.\d{1,4})?)$/;
				var validator = function(value){
					if(value.toString().length > 0 && (parseFloat(value) === 'NaN' || !regex.test(parseFloat(value)))){
						ctrl.$setValidity('decimalValidation',false);
					}
					else {
						ctrl.$setValidity('decimalValidation',true);
					}
					return $window.parseFloat(value) ? ''+value : value;
				};
				ctrl.$parsers.push(validator);
				ctrl.$formatters.push(validator);
			}
		}
	}])

**Comment by jonsamwell** [comment]
Hi! Thanks for using the module.

I think there are two issue here.

1) The first validator function is doing too much (I think).  I don't think you need to be setting ctrl to invalid or setting the external validation in this function as this is what the rest of the angular pipeline does.  You also need to supply a key to the first parameter  in the $setValidity (this is why the null message is appearing.  I think it is enough to do this:

```
 .directive('cfNumber', ['validationManager', '$window',function(validationManager, $window) {
        return {
            restrict: 'A',
            require: 'ngModel',
            priority: 100,
            link: function($scope, iEl, iAttrs, ctrl) {
                $scope.precision = 4;//$scope.input.options.precision;
                var regex = /^\d+(()|(\.\d{1,4})?)$/;
                var validator = function(value){
                        if(value.toString().length > 0 && (parseFloat(value) === 'NaN' || !regex.test(parseFloat(value)))){
                            ctrl.$setValidity('invalidPrecision', false);
                           return undefined;
                        } else {
                            ctrl.$setValidity('invalidPrecision', true);
                           return value
                        }
                    };
                ctrl.$parsers.push(validator);
                ctrl.$formatters.push(validator);
            }
        }
    }])
```

So the second problem is how do you get a scope value to appear in the validation message?  Out of the box you can't however we can extend things a little by doing a custom error message resolver (this is the thing that gets the error message for a given error key).  I'll have a little think how to do this and get back to you tomorrow as we might have a few scope issues?

http://jonsamwell.github.io/angular-auto-validate/#custom_error_resolver

Hope this is enough to get started with.

Jon

**Comment by imomin** [comment]
Thanks for your help but end up with different option. However, I am still interest in sending attribute value or scope value in the validation message.
