### ISSUE TITLE
Fields that are touched and set invalid but do not change in value lack errors.

### ISSUE THREAD

**Issue by pjwalmsley** [jonsamwell/angular-auto-validate#44]
Particularly; If i were to set required on a field, click into, then click to another field.  

In this case, validation occurs in angular marking the field invalid, but we do not style the field differently or show the relevant error.  

I'm looking into addressing this.  I added 
```javascript
element.bind('blur', function(){
    ngModelCtrl.$setTouched();
    validationManager.validateElement(ngModelCtrl, element);
});
```
to the ngModelDirective decorator hook.  This fires when a user click in then clicks out as well as when a user tabs through/by the field.  I set $touched here because it is not set until after validations occurs.  

I modified validateElement 's needsValidation variable to check if the element has been touched as follows.

    needsValidation = !modelCtrl.$pristine || modelCtrl.$touched || forceValidation,

That behavior is inline what I want.

Sidenote: I noticed we have a variable for isValid set to !modelCtrl.$invalid in the validateElement function.  We should just check modelCtrl.$valid instead.  

The main role of this bugfix for me is to address the required validation.  If a field is not required and nothing is less than are min, do we care?  Possibly...

Anyways, do you guys have any feedback on my approach?  
Do you agree it is better practice/UX to validate when an element is touched even if nothing changes?  
Is debounce not firing in this case considered a bug with angular/should it be brought up there?
Do you think validate on touched should be an option/configurable or default?  Imo it should be default, but i'm bias. :p

Anyways looking to do a pull request if you guys feel this would be valuable.

**Comment by pjwalmsley** [comment]
A fix was implemented on my branch in commits: 27a633a 9f64413 065d1e0 5ed8c6b .  Atempted to do a pull request but I didn't do it right (didn't branch).

**Comment by jonsamwell** [comment]
This seems like angular behaviour to me?  I don't think we should be setting touched as I would expect angular to do this?  If you want it to validate on blur you can use the ngModelOptions.  I have lots of apps that successful validate the required field when the use focuses the element, doesn't put anything in and then tabs out?

The app I'm working on at the moment definately does this.  However, I have a custom bit of code to make blur the default updateOn action.

```
function InputUpdateTriggerFn($sniffer) {
  return {
    restrict: 'E',
    require: 'ngModel',
    priority: 99,
    link: function(scope, elm, attr, ngModelCtrl) {
      var ngModelOptions = {
        updateOn: 'blur'
      };

      if (attr.type === 'radio' || attr.type === 'checkbox') {
        return;
      }

      if (attr.ngModelOptions) {
        ngModelOptions = scope.$eval(attr.ngModelOptions);
      }

      if ($sniffer.hasEvent('input')) {
        elm.unbind('input');
      }

      elm.unbind('keydown').unbind('change');

      elm.bind(ngModelOptions.updateOn, function() {
        scope.$apply(function() {
          ngModelCtrl.$setViewValue(elm.val());
        });
      });
    }
  };
}

InputUpdateTriggerFn.$inject = [
    '$sniffer'
];

angular.module(app.modules.core.name).directive('input', InputUpdateTriggerFn);

```

After I tab out without putting any value in the textbox it is validated and set to ng-dirty.

Sorry if I'm not understanding you!

PS if you are going to do a pull request (which would be awesome) it needs to be tested in angular 1.2 and 1.3.  Make sure the pull request only changes one thing so it's easier to understand :-)

**Comment by jonsamwell** [comment]
Also I don't think we could put the blur event handler in the main code as some user might not want this and this is kind of why the ngModelOptions is supported (even in angular 1.2)

**Comment by jonsamwell** [comment]
Also if you look at the angular source code it is setting touched on blur

https://github.com/angular/angular.js/blob/master/src/ng/directive/ngModel.js#L1041

**Comment by jonsamwell** [comment]
This seems to be the point in the angular source code where on an element with the blur event for the updateOn property in the ngModelOptions where angular decides if it should set the control as dirty and continue with the validation phase.  As you can see if the value is undefined (which it will be when you enter and blur the control with no value in it) it just returns and doesn't run the validation phase.  I would submit a change request to angular to get them to put something in the ngModelOptions to override this behaviour i.e. allowUndefined.

https://github.com/angular/angular.js/blob/master/src/ng/directive/ngModel.js#L654

My directive above gets around this.

**Comment by pjwalmsley** [comment]
Yea, that approach does seem a bit better.  I'll give the change request a go and see how that works out.

**Comment by jonsamwell** [comment]
Cool - let me know how you get on!
