### ISSUE TITLE
frmOptions is undefined

### ISSUE THREAD

**Issue by sberube** [jonsamwell/angular-auto-validate#45]
When using version 1.7.23 of the plugin I get the error message "frmOptions is undefined". After investigation I found that the getFormOptions function return undefined, is it normal? 

By browsing the source code I've seen that version 1.7.22 introduces a breaking change on the function that is currently failing. Do I need to do something on my side to resolve this issue?

Thanks!

**Comment by jonsamwell** [comment]
Hi,

Are the elements you are validating wrapped in a form element?

**Comment by jonsamwell** [comment]
I think perhaps I need to provide a default frmOptions object if there isn't a parent form.

**Comment by sberube** [comment]
Yes, the elements I try to validate are in a form element. We were using version 1.4.20 of the plugin before and everything worked fine.

**Comment by sberube** [comment]
Actually, the problem seems to be that the autoValidateFormOptions object on the FormController is not built (it is undefined).

**Comment by jonsamwell** [comment]
Yep, I just noticed it hasn't gone out in the build - fixing now :-)

**Comment by jonsamwell** [comment]
This should now be fixed in v1.18.01 (it is up on bower as well)

**Comment by jonsamwell** [comment]
Hi @sberube sorry you'll have to use the latest version now v1.18.02 which fixes an issue where a control didn't have a parent form.  Let me know if you are still getting any issues.
