### ISSUE TITLE
disable-dynamic-validation directive does not work on sub forms

### ISSUE THREAD

**Issue by pjwalmsley** [jonsamwell/angular-auto-validate#46]
Working around it right now by overriding the styles and hiding the classes. 

Particularly it would be great to allow the user to pass a variable (in addition to no variable being allowed) to disable/enable validation dynamically.  This would allow users to enable/disable validation error message rendering for subforms when they enable/disable the subforms. :)

**Comment by jonsamwell** [comment]
Hi @pjwalmsley,

How have you declared the subform is it an element or an attribute i.e. <div ng-form> this should work if you are using the form or ng-form as an element.  Currently the directive only supports elements so I'll add the attribute as a restriction.

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/directives/autoValidateFormOptions.js#L37

Jon

**Comment by jonsamwell** [comment]
Hi @pjwalmsley I've fixed this locally just pad out the tests and push up

**Comment by jonsamwell** [comment]
Fix now commit in latest release (v1.18.30
