### ISSUE TITLE
Add asterix to required elements

### ISSUE THREAD

**Issue by mgsstms** [jonsamwell/angular-auto-validate#47]
Is it possible to add asterix to required elements?

**Comment by jpmckearin** [comment]
This has already been answered. Go [here](http://jonsamwell.com/dynamic-angularjs-validation/) and search for the comment made by Zane Gers.

**Comment by mgsstms** [comment]
Thank you for your response. To use the extra directive is not the best idea for me.
Actually I implemented this feature myself, but it doesn't work inside of <tabset>.

**Comment by mgsstms** [comment]
1. I put functions after this function " setElementValidationError = function (element, errorMsgKey, errorMsg) " 

-------------------
                    addAsterixToElement = function (scope, modelCtrl, el) {
						var isSetAsteriskForRequiredLabel = true;
						var asteriskStr = '*';
						var is_required = el.attr('ng-required');
						is_required = (is_required === true) || (is_required === 'true');
						if (isSetAsteriskForRequiredLabel && is_required) {
							var labels = document.querySelectorAll('label[for="' + el.attr('name') + '"]');
							// if nothing is found check previous element
							if (!labels || labels.length < 1) {
								var elBefore = el[0].previousElementSibling;
								if (elBefore && elBefore.tagName === 'LABEL') {
									labels = [elBefore];
								}
							}

							// set asterisk for match(es)
							if (labels && labels.length > 0 && el.attr('type') !== 'radio' && el.attr('type') !== 'checkbox') {
								for (var i = 0; i < labels.length; i++) {
									var label = labels[i];
									// don't append twice if multiple inputs with the same name
									if (label.innerText.slice(-asteriskStr.length) !== asteriskStr) {
										label.innerText = label.innerText + asteriskStr;
										$compile(label)(scope);
									}
								}
							}

						}
					},

                    addAsterixToFormElements = function (scope, frmElement) {
                        var frmCtrl = frmElement ? angular.element(frmElement).controller('form') : undefined,
                            processElement = function (ctrlElement) {
                                var controller;
                                ctrlElement = angular.element(ctrlElement);
                                controller = ctrlElement.controller('ngModel');

                                if (controller !== undefined) {
                                    if (ctrlElement[0].nodeName.toLowerCase() === 'form') {
                                        // we probably have a sub form
                                        addAsterixToFormElements(scope, ctrlElement);
                                    } else {
                                        var isAdded = addAsterixToElement(scope, controller, ctrlElement);
                                    }
                                }
                            };

/*                        if (frmElement === undefined || (frmCtrl !== undefined && frmCtrl.disableDynamicValidation)) {
                            return;
                        }*/

                        // IE8 holds the child controls collection in the all property
                        // Firefox in the elements and chrome as a child iterator
                        angular.forEach((frmElement[0].all || frmElement[0].elements) || frmElement[0], function (ctrlElement) {
                            processElement(ctrlElement);
                        });

                        // If you have a custom form control that should be validated i.e.
                        // <my-custom-element>...</my-custom-element> it will not be part of the forms
                        // HTMLFormControlsCollection and thus won't be included in the above element iteration although
                        // it will be on the Angular FormController (if it has a name attribute).  So adding the directive
                        // register-custom-form-control="" to the control root and autoValidate will include it in this
                        // iteration.
                        if (frmElement[0].customHTMLFormControlsCollection) {
                            angular.forEach(frmElement[0].customHTMLFormControlsCollection, function (ctrlElement) {
                                // need to force the validation as the element might not be a known form input type
                                // so the normal validation process will ignore it.
                                processElement(ctrlElement);
                            });
                        }
                    },
------------
2.I put declarations after this line " resetForm: resetForm"
----------------
                    ,addAsterixToElement:addAsterixToElement,
                    addAsterixToFormElements: addAsterixToFormElements
---------------

3. Used addAsterix after this line " link: function (scope, el) {"
-------------               
                    validationManager.addAsterixToFormElements(scope, el);
-------------

**Comment by mgsstms** [comment]
I guess, the problem  that I use wrong scope here: "$compile(label)(scope);"

**Comment by jonsamwell** [comment]
I can't recommend using this approach as it modifies the library itself and will be incompatible and unmanageable when upgrading to future versions.  I would suggest a directive approach for this as it could easily be pulled out into a directive.

**Comment by mgsstms** [comment]
Thank you. I agree with you. I already developed clean directive for ngRequired to add asterix (html ).

**Comment by jonsamwell** [comment]
Great

**Comment by mgsstms** [comment]
I guess, it could be used in module
app.directive('ngRequired', ['$compile', function($compile) {
	return {
		restrict: 'A',
		link: function(scope, element, attrs) {
			function updateLabel(isRequired) {
				//var asteriskRemove = '.required';
				var asteriskAppend = '<span class="required">&nbsp;*</span>';
				var asteriskTxt = '*';
				if (!attrs.id) {
//console.log('No id attribute', attrs);
					return;
				}
				
				var labels = document.querySelectorAll('label[for="' + attrs.id + '"]');
				// if nothing is found check previous element
				if (!labels || labels.length < 1) {
					var elBefore = element[0].previousElementSibling;
					if (elBefore && elBefore.tagName === 'LABEL') {
						labels = [elBefore];
					}
				}
				
				// set asterisk for match(es)
				if (labels && (labels.length > 0) && (attrs.type !== 'radio') && (attrs.type !== 'checkbox')) {
					for (var i = 0; i < labels.length; i++) {
						var label = labels[i];
						var txt;
						if ((label.textContent) && (typeof (label.textContent) != "undefined")) {
							txt = label.textContent;
						} else {
							txt = label.innerText;
						}
						var hasAsterisk = txt.slice(-asteriskTxt.length) === asteriskTxt;
						if (!hasAsterisk && isRequired) {
							angular.element(label).append(asteriskAppend);//$compile(asteriskAppend)(scope));
						} else if (hasAsterisk && !isRequired) {
							//doesn't work: angular.element(label).remove(asteriskRemove);
							//doesn't work: $compile(asteriskAppend)(scope).remove();
							label.outerHTML = label.outerHTML.replace(asteriskAppend, '');
						}
					}
				}
			}

			attrs.$observe('required', function(value) {
				updateLabel(value);
			});
		}
	}
}]);
