### ISSUE TITLE
TypeError: Cannot read property 'forceValidation' of undefined

### ISSUE THREAD

**Issue by rwwagner90** [jonsamwell/angular-auto-validate#49]
I can't even get started using this. Getting an error: "TypeError: Cannot read property 'forceValidation' of undefined"

Any ideas?

**Comment by jonsamwell** [comment]
What version are you using?

**Comment by rwwagner90** [comment]
1.17.23

**Comment by rwwagner90** [comment]
More info:

I'm using foundation, and I included:
```js
.run([
    'validator',
    'foundation5ElementModifier',
    function(validator, foundation5ElementModifier) {
      debugger
      validator.setDefaultElementModifier(foundation5ElementModifier.key);
    }])
```

I'm trying to load a page with my form on it when I get that error.

**Comment by jonsamwell** [comment]
Sorry there is a bad build with that version.  Updgrade to the latest one v1.18.02

**Comment by rwwagner90** [comment]
It appears that version is not available:

```bash
bower angular-auto-validate#~1.18.02     ENORESTARGET Tag/branch ~1.18.02 does not exist

Additional error details:
Available tags: V1.0.1, V1.0.2, v1.0.0, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.18, v1.0.19, v1.0.20, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9, v1.10.21, v1.11.21, v1.12.21, v1.13.22, v1.14.22, v1.15.22, v1.16.22, v1.17.23, v1.18.01, v1.18.02, v1.2.20, v1.3.20, v1.4.20, v1.5.20, v1.6.20, v1.7.21, v1.9.21
Available branches: gh-pages, master
```

Should I do 1.9.21?

**Comment by jonsamwell** [comment]
Hmmm, just looking - there is a tag with that version number

**Comment by rwwagner90** [comment]
Ah, haha, yeah there is. Well, is there a reason I shouldn't use the newer 1.9.21 one?

**Comment by jonsamwell** [comment]
It's not newer it is really old - you could use 1.16.22 that is a good version.  Give me 5 minutes looking at it now

**Comment by rwwagner90** [comment]
Ah, I was confused, as I thought the order it spit them out in was the order of versions. I tried putting the "v" in front of the version and it appears to work.

**Comment by rwwagner90** [comment]
Also, thanks so much for responding so quickly. Very helpful.

**Comment by jonsamwell** [comment]
Sorry you had a problem getting started! That definitely not what I want.  I'm just sorting out the bower issue now.  I might add a simple plunker link to the readme so it is easy to get started.  Let me know if you need anymore help!!!

**Comment by rwwagner90** [comment]
No worries. It's already a lot easier than what I was using before. Great library so far. A plnkr might be helpful, and/or perhaps a couple more examples on the docs. As far as I could tell, no common validations are included correct? Like checking for email, etc? That may be to cut down on bloat, not sure, but including an email checker, as well as a way to check a password and confirm password are equal, might be some nice common use cases to include out of the box. Shouldn't be hard to wire up, as I can write custom ones for it, but just thinking out loud here.

**Comment by jonsamwell** [comment]
Yeah I'll sort out a plunker.  The library is for the processing of angular validation and displaying the results to the user rather than doing any actual validation.  That being said it includes default error messages to all the built in angular validator.  Angular has a built in email validator if you have an input with type email it should work.

**Comment by jonsamwell** [comment]
All the bower version issues should now be fixed.

bower install --save-dev angular-auto-validate

should now resolve to the latest release v1.18.3

Thanks!
