### ISSUE TITLE
Option for allowing hidden elements to be validated

### ISSUE THREAD

**Issue by jpmckearin** [jonsamwell/angular-auto-validate#51]
I know this initially sounds like something that would never be necessary, but when using a third party control set I ran into this. Specifically, almost any third party solution for select elements use a stylized form of a list and hides the actual select element. I forked this repo and created that configuration functionality but have not yet built tests. Feel free to take a look. [jmckearin/angular-auto-validate](https://github.com/jpmckearin/angular-auto-validate)

Disclaimer: Ignore any version changes that I did.

**Comment by jonsamwell** [comment]
Hi @jpmckearin 

I actually added this functionality to the library a few days ago!

It can be configured on a global on form basis to validate hidden elements.  I need to update the documentation but in short.  To validate hidden elements on a form add the attribute

```
<form novalidate ng-sumbit="vm.submit()" validate-non-visible-controls>...<form>
```

See this directive (for the form and ng-form elements)

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/directives/autoValidateFormOptions.js#L12

You will also be able to change the default value for the validateNonVisibleControls option property by setting the value against the validator provider (in a config block).

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/providers/validator.js#L278
