### ISSUE TITLE
ng-submit required?

### ISSUE THREAD

**Issue by phazei** [jonsamwell/angular-auto-validate#53]
Is there a way to get the form to validate without ng-submit?

I'm using ngUpload, and it also uses a submit event listener to do its submission, so I'm not using ng-submit at all.  ngUpload does check to make sure formController.$valid is true before submitting, then it returns false.  After that auto validate doesn't appear to be triggered.  (This is separate from #52 where I removed ngUpload entirely just trying to get it working with the most basic settings.)

**Comment by jpmckearin** [comment]
I did something very similar to #40 in order to solve a similar issue.

**Comment by jonsamwell** [comment]
Yep this is exactly what I was going to suggest.

**Comment by phazei** [comment]
Wow, that was a fast response.

Actually, I just got it working with the 1.0.17 version by just adding an empty "ng-submit" to the form.
