### ISSUE TITLE
Global disable validations should be override-able at the form level

### ISSUE THREAD

**Issue by pjwalmsley** [jonsamwell/angular-auto-validate#59]
I've been having trouble using 'validator.enable(false)' to enable automatic validations in combination with the 'auto-validate-enabled="true"' attribute on a form as described on line 77 of the dist file.

I believe the I believe in a past version i had used the 'disable-dynamic-validation="false"' attribute on the form.  

The parseOptions method on line 1036 of the dist file sets the disabled flag whenever the global flag is set OR the form level flag is set.  It never checks for the 'auto-validate-enabled' flag.

```javascript
    function parseOptions(ctrl, validator, attrs) {
        var opts = ctrl.autoValidateFormOptions = ctrl.autoValidateFormOptions || angular.copy(validator.defaultFormValidationOptions);
        opts.forceValidation = false;
        opts.disabled = !validator.isEnabled() || parseBooleanAttributeValue(attrs.disableDynamicValidation);
        opts.validateNonVisibleControls = parseBooleanAttributeValue(attrs.validateNonVisibleControls);
        opts.removeExternalValidationErrorsOnSubmit = attrs.removeExternalValidationErrorsOnSubmit === undefined ? true : parseBooleanAttributeValue(attrs.removeExternalValidationErrorsOnSubmit);
    }
```

**Comment by jonsamwell** [comment]
Sorry the doc on that are out of date.  You should be using the attribute disable-dynamic-validation="false" to re-enable a form or use true to disable it.

see my comment on https://github.com/jonsamwell/angular-auto-validate/issues/61

**Comment by jonsamwell** [comment]
This is now working in the latest release v1.18.6

**Comment by pjwalmsley** [comment]
Thanks Jon!
