### ISSUE TITLE
findWithClassElementAsc 

### ISSUE THREAD

**Issue by pjwalmsley** [jonsamwell/angular-auto-validate#60]
line 322 of the dist file fails to find the form group element.  Our element is 4 or 5 divs deep from the form-group for layout purposes.  This should be a higher limit.

**Comment by jonsamwell** [comment]
which version are you using?

**Comment by jonsamwell** [comment]
I think a recursive limit property would be good for this.

**Comment by jonsamwell** [comment]
I've increased this to 10 for now

**Comment by pjwalmsley** [comment]
Thanks.  That sounds reasonable. :)
