### ISSUE TITLE
Globally disabled validation is still validating some forms

### ISSUE THREAD

**Issue by dsargent3220** [jonsamwell/angular-auto-validate#61]
We are lazy loading Angular UI grid (not ng-grid, the beta of UI grid) using OC Lazy Load (not sure if that bit is relevant or not).
When we turn on filtering in the grid it adds text boxes to the top of the grid header.  Those text boxes are used to filter the columns / rows and do not have form-group class.
We decided we wanted to turn off validation globally and then just apply it via the form  tag to those forms we want validated.  This is not working and I've confirmed it's still trying to validate these input boxes.
We've upgraded to 1.18.5 and that fixed the form validation being shut off for other sub forms, but not for this one.

**Comment by dsargent3220** [comment]
I've removed all of the lazy loading stuff and it still does it, so definitely not OcLazy load.

**Comment by dsargent3220** [comment]
A further problem.  Not only is it validating form elements that it should not be . . . but one of the forms that it isn't validating also won't validate when we set the form to validate by adding
auto-validate-enabled="true"
to the form tag.
Either we are doing something hideously wrong, or it's totally broken.

**Comment by jonsamwell** [comment]
Hi,

Unfortunately I'm on holiday until mid next week so can't really look at this but if you could do me a reproducing plunker I will look at it and fix the library as soon as I get back.

One thing to note (as the documentation needs updating) is that the attribute auto-validate-enabled does not exist.  To enable / disable a form you would use the attribute disable-dynamic-validation="false" on the form element.  There is a single directive that is applied to a form which collects all the options for the library so you might want to have a look here.

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/directives/autoValidateFormOptions.js#L11

Try that new attribute and let me know hot you get on.

Thanks,

Jon

**Comment by dsargent3220** [comment]
OK.  Here is the Plunker
http://plnkr.co/edit/bF0TDi2MvLNea4QpuPco

To recap, here's what we are seeing:
* Setting validator.enable(false); turns off validation for forms but does not keep the validator from throwing errors for inputs that do not have parent form-group class
*  There appears to be no way truly globally disabling validation and then turning it back on for only certain forms.

What we'd like to see:
We'd like to be able to disable global validation, in this mode the validator would do NOTHING unless it found a form tag with a property that turns it on for that form.  If there are sub forms under that form then it would not validate those unless they had that property as well.  And above it, it should not be throwing errors on input's that do not have a form-group class unless they are in a form that is being validated.  Note: that those errors make typing in those boxes very difficult as keystrokes get thrown away and you have to press keys repeatedly (firefox, maybe others)

**Comment by jonsamwell** [comment]
I've fixed a few issues and the plunkr appears to be working fine now with the new release file (v1.18.6).

Let me know if you are still having any issues.

**Comment by dsargent3220** [comment]
Jon, thank you so much for getting to this.  You've fixed the main issue of it trying to validate inputs that are not inside of forms but there is still a bug with turning off validation all together then just enableing it for individual forms.
I've updated the plunker
http://plnkr.co/edit/bF0TDi2MvLNea4QpuPco?p=preview
Notice that we are turning validation off in the config and that the Username and password form now does not have any special validation flags set to turn it on and yet it is still being validated.

Let me know if I'm missing something.

**Comment by jonsamwell** [comment]
Great I'll take a look.

**Comment by slupekdev** [comment]
Try change autoValidateFormOptions.js file:
replace line 15 :
`if (validator.isEnabled() === false && parseBooleanAttributeValue(attrs.disableDynamicValidation) === false) {` 

with

 `if (validator.isEnabled() === false && attrs.disableDynamicValidation === 'false') {`

**Comment by jonsamwell** [comment]
@slupekdev That would do the same thing.  Or am I missing something?

**Comment by jonsamwell** [comment]
@slupekdev - I seem what you meant with the above code.  Thanks for looking at the issue.

This issue is now fixed in latest release https://github.com/jonsamwell/angular-auto-validate/releases/latest
