### ISSUE TITLE
General error validation

### ISSUE THREAD

**Issue by jonagoldman** [jonsamwell/angular-auto-validate#63]
I want to show a general error message when something goes wrong or when I don't want to specify in which field the validation failed occurred.

Here is an example response from the server, if its helps.

![image](https://cloud.githubusercontent.com/assets/1297559/7394576/1814dc7a-ee9d-11e4-9214-6ecafa5a73c6.png)

One option is to add a hidden empty field and assign to it a default key, but I am sure there is a better more elegant way.
Thanks.

**Comment by jonsamwell** [comment]
Hmmm, you could override the default message (https://github.com/wkwiatek/angular-auto-validate/blob/foundation-append-element/src/services/defaultErrorMessageResolver.js#L21) in the error message resolver as a work around but it would be good to have the library handle this.  You could create a custom error message resolver which provides this behaviour.  See http://jonsamwell.github.io/angular-auto-validate/#custom_error_resolver

**Comment by jonsamwell** [comment]
A custom message resolver is the way to go I think.
