### ISSUE TITLE
Errors in Foundation element modifier are appended to column

### ISSUE THREAD

**Issue by wkwiatek** [jonsamwell/angular-auto-validate#65]
I've just started to use your `angular-auto-validate` and met first problem. There is _Foundation_ based grid in project and it was a perfect choice to use `foundation5ElementModifier`. However there's an issue with that. It requires to have an `columns` class to be present but I think it's not required in _Foundation_. 

Wouldn't it be better to add error messages right after input field? Or will it produce any problems?

**Comment by wkwiatek** [comment]
I made this improvement for myself but I'm not sure whether it satisfies your requirements. You can take at look at: https://github.com/wkwiatek/angular-auto-validate/tree/foundation-append-element and compare across forks.

**Comment by jonsamwell** [comment]
Hi, thanks for using the library.  The foundation5ElementModifer uses the best practives from that library but you are right you wouldn't have to use columns.  I think the solution would be to create a custom element modifier but if you have modified the existing on and the test still pass feel free to send in a PR.
