### ISSUE TITLE
Validation might have an option to start validating on submit

### ISSUE THREAD

**Issue by wkwiatek** [jonsamwell/angular-auto-validate#66]
It would be nice to have an option to choose whether validation should start immediately or after first click on submit. In **AngularJS 1.3** it is pretty easy to check as form has proper value set in `$submitted` flag. 

The way to check fields after first submit is really nice from UX perspective as it doesn't mess with form until user enters something wrong.

**Comment by gregbty** [comment]
I agree this would be great. Having the ability to set it globally if we wanted to have it validate at $touched would be great as well.

**Comment by jonsamwell** [comment]
Yes this would be a great feature.  Feel free to send in a PR - I'm really really snowed under at the moment so it might be a while until I get around to it sorry!

**Comment by wkwiatek** [comment]
I've just added PR with changes that we are currently using in our app and works pretty fine for us. There is a little bit more than just this issue and #65 so please review that in your spare time. Thanks!

**Comment by jonsamwell** [comment]
Thanks for the PR it's really helpful, I'll try and take a look tomorrow :-)

**Comment by jgesser** [comment]
It would be really great have this feature. Any news about merging the PR?
Thanks!

**Comment by jonsamwell** [comment]
@jgesser I was having a look today at @wkwiatek branch with this in.  Unfortunately the PR with it is massive and contains lots of other functionality so it will be a hard one to merge.  I'll look at just getting this in this evening.

**Comment by jgesser** [comment]
great @jonsamwell :)
I can make some tests when it is done.

**Comment by jonsamwell** [comment]
@jgesser @wkwiatek This in finally working (sorry for the delay).  You'll find it in the latest release (v1.18.13) and here is a working plunker http://plnkr.co/edit/S5YTRYPQM8unAjDHLsxR?p=preview

Basically just add the attribute 'validate-on-form-submit="true"' to the form node.

```
<form novalidate="novalidate" ng-submit="onSubmit()"
      validate-on-form-submit="true">
  <div class="form-group">
    <label for="exampleInputName">Name</label>
    <input type="text" class="form-control" id="exampleInputName" placeholder="Name" ng-model="vm.model.name" required="" ng-minlength="6" ng-maxlength="255" />
  </div>
  <div class="form-group">
    <label for="exampleInputEmail">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail" placeholder="Email" ng-model="vm.model.email" required="" />
  </div>
  <button type="submit" class="btn btn-default">Submit Form</button>
  <button type="reset" class="btn btn-secondary">Rest Form</button>
</form>
```

Or you could just change the libraries default value for it here

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/providers/validator.js#L275

```
   function RunFn(validator) {
      validator.defaultFormValidationOptions.validateOnFormSubmit = true;
    }
    
    RunFn.$inject = [
      'validator'
    ];
   
    app.config(RunFn);
```

**Comment by jonsamwell** [comment]
I'll be adding this to the new documentation I'm doing in the next few days.

**Comment by wkwiatek** [comment]
Thanks!

**Comment by jgesser** [comment]
Thank you @jonsamwell .

The configuration through the attribute is working very nice.

But changing the default options isn't working as expected because the default values are overwritten in the function parseOptions, just after have been copied:
https://github.com/jonsamwell/angular-auto-validate/blob/master/src/directives/autoValidateFormOptions.js#L11

Please let me know if I am doing something wrong.

**Comment by jonsamwell** [comment]
Hi @jgesser no you aren't doing anything wrong that is definitely another bug.  Fixing it now :-)

**Comment by jonsamwell** [comment]
@jgesser I've now fixed this get the new release (v1.18.14) and it is working.  I've done a plunker as a working example http://plnkr.co/edit/1aNcoJkWfpMpfJrcXS2T?p=preview

**Comment by jgesser** [comment]
Great @jonsamwell.
Working perfectly now.
Thanks!

**Comment by jonsamwell** [comment]
Awesome!
