### ISSUE TITLE
ngForm in ngRepeat throws error "Error: [$compile:ctreq] Controller 'form', required by directive 'ngForm', can't be found!" (potentially due to usage of ngInclude? ui-router?)

### ISSUE THREAD

**Issue by freeedom** [jonsamwell/angular-auto-validate#67]
Hi there, first of all, great library very useful (why not more stars ?)

Though, I'm trying to create a list of  < ANY ng-repeat="x in list" ng-form="formName{{$index}}" >  and as soon as I use "jcs-autoValidate" module it throws me this error 
"Error: [$compile:ctreq] Controller 'form', required by directive 'ngForm', can't be found!" 

The debugger in chrome, after some tries, seems maybe to relate this  to usage of ng-include, first, and secondly to usage of  <ui-view> directive of angular-ui-router in which all my app is rendered (after trying moving the specific code around).

I was wondering if this was some known issue? I mean a ng-repeat + ng-form seems quite common... Auto-validate should work with that right ?

Thanks a lot for any help.

**Comment by freeedom** [comment]
And just for help if anyone stomps on the same issue : there's always the workaround of specyfing a ng-form or <form> AROUND the list of the ng-repeat (effectively there will be only one form/ngForm) and using the $index of the ng-repeat on each and every input INSIDE the ng-repeat to make them distinguishable between each row. 

The downside being ofcourse that, by default, if ANY input inside the whole form is invalid, the whole form will be invalid (as many rows as there are, not only one row).

**Comment by jonsamwell** [comment]
Hmm, could you do a plunkr to reproduce and I'll take a look and see if there is anything the library can do to help?

**Comment by freeedom** [comment]
Hi thanks for feedback. Here is a example 

http://plnkr.co/edit/HULuG7dw4GvlD03D86Wb

See, there is this error  
Error: [$compile:ctreq] Controller 'form', required by directive 'ngForm', can't be found!
even if there is a <form> higher in the HTML. ngForm itself doesn't require a <form> as far as I know (which is what the first example does on the plunkr)

https://docs.angularjs.org/api/ng/directive/ngForm

Thanks a lot!

(on a side note, the input on the second form that is outside the ngRepeat doesn't seem to validate at all neither..any idea maybe?)

**Comment by ruscinc** [comment]
fabm22 , you said that was using 
```< ANY ng-repeat="x in list" ng-form="formName{{$index}}" >```
 I had the same problem and I fixed dividing in two directives:
```< div ng-repeat="x in list">```
```<ng-form="formName{{$index}}" >```

ngForm directive  is actually an alias for the form directive required, and can be referenced using any of these:

```<ng-form></ng-form>
<div ng-form></div>
<div x-ng-form></div>
<div data-ng-form></div>```

**Comment by jonsamwell** [comment]
@ruscinc sounds like a sensible solution
