### ISSUE TITLE
Overriding Error Messages for specific element doesn't work

### ISSUE THREAD

**Issue by mgsstms** [jonsamwell/angular-auto-validate#69]
adding the attribute *-err-type="errorTypeKey" doesn't work

for instance,
input type="text" ng-model="model.firstname"  required  required-err-type="firstNameRequired"/

In this case you will see this error message: "Please add error message for required"

**Comment by jonsamwell** [comment]
Could you do a reproducing plunkr as it is working in two apps I have it in.  Have you added the custom error message to the message collection?

**Comment by mgsstms** [comment]
Thank you. I forgot to add the custom error message to the message collection. I added it directly to 
attribute required-err-type. Not it fixed.
http://plnkr.co/edit/vcpSe0TuNJRyxutfOpo4?p=preview
Thank you again.

**Comment by jonsamwell** [comment]
Cool, glad it works :-)
