### ISSUE TITLE
Weird behavior upon using auto-validate with angular-ui-router injected views.

### ISSUE THREAD

**Issue by amcpanaligan** [jonsamwell/angular-auto-validate#74]
Hi, I want to use jcs-autoValidate for form validation as it saves time writing html elements for validation blocks. I am using angular-ui-router to inject views with its associated controller.

I have written a form in a particular view using <form> tags with novalidate attribute and <button type="submit"> as indicated on jcs-auto-validate demo site which is this is the simplest mark up for the auto validation to work. Placed a view required="required" attribute in my textboxes, upon submitting the form with missing required fields, it's good because it doesn't execute the method under my attribute ng-submit="method()" in my form. However, it doesn't also display the error messages of the required inputs.

Also, I have used bootstrap angular directive for a time picker, the jcs-autoValidate resets its value upon submit.

**Comment by jonsamwell** [comment]
Could you do a reproducing plunkr?

**Comment by jonsamwell** [comment]
Any progress on the Plunker?

**Comment by jonsamwell** [comment]
No plunker so can't replicated.  Please re-open when you have an example

**Comment by jonsamwell** [comment]
PS I've changed the way the ngModelDecorator works which was causing a problem with other angular libraries (angular-material) so it might be worth trying this again.
