### ISSUE TITLE
Form Group Warning Error & Insert After

### ISSUE THREAD

**Issue by origin1tech** [jonsamwell/angular-auto-validate#77]
Two things I'm seeing is that I'm getting a warning noting that auto-val needs input to be wrapped in form-group. I haven't looked at how its crawling up the elements but its giving me a false positive as all inputs are in fact wrapped in form group.

Lastly it seems as thought when validation messages are "inserted after" the input its not taking into account for example a checkbox where text may be after the input.

I would think it would be best to find the last element in the parent and insert after the last index. Mind you this isn't an exact science and I get that but I would think it might be a better approach in general.

**Comment by jonsamwell** [comment]
I think if you have a specific scenario it would be best to create a custom element modifier which does the placement specifically for you application's form structure as everyone codes bootstrap slightly differently.  Let me know if you need a hand with the code for this, but see the documentation first :-)

http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers

**Comment by origin1tech** [comment]
thx Jon and I’m serious about this feature/extension etc. happy to work on it as time permits and release it for all.

So if you could shoot me some links as to where to start I can probably take it from there at least initially.

this need really has come from being on the road of late and well when you go from 3-4 windows on ur desktop to one that’s barely 14/15 inches, real estate is a premium, I’m sure u get that.

**Comment by jonsamwell** [comment]
Sure, I'd suggest a new standard dom modifier or options on the current BS3 modifier to allow you to place the message after the input element.

Here is the source for the current BS3 one.

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/services/bootstrap3ElementModifier.js

and here are the current tests for it

https://github.com/jonsamwell/angular-auto-validate/blob/master/tests/services/bootstrap3ElementModifier.spec.js

and here is the documentation for the element modifiers.  If you add options to the current BS3 one well need to add a few lines to the documentation to explain the new properties.

http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers

Looking forward to seeing what you come up with!
