### ISSUE TITLE
Is it possible to publish this to npm? 

### ISSUE THREAD

**Issue by jebner** [jonsamwell/angular-auto-validate#78]

**Comment by jonsamwell** [comment]
Sure - off out now but I'll try and do this tomorrow

**Comment by jebner** [comment]
I wanted to ask you again, if you could publish this. I'd really use it and I'd be very grateful. 
If it is easier for you, you can also add me as contributor and then I can publish it myself.

Thanks a lot!

**Comment by jonsamwell** [comment]
Sure sorry for the delay! I promise I'll get this published to npm tomorrow
:-)

**Comment by jonsamwell** [comment]
Done!

https://www.npmjs.com/package/angular-auto-validate
