### ISSUE TITLE
Can't get angular-auto-validate working

### ISSUE THREAD

**Issue by Hooyek** [jonsamwell/angular-auto-validate#79]
Hello,

I'm new on github, I really like your module and I want to add it to my test project (My first angular project BTW).
And I have a problem here because I installed it, and it's not working. Tried to add some console logs inside your project but none of them is logging. I even created plunkr, but in plunkr everything works fine (http://plnkr.co/edit/4VmLrq6OSbyMTkjPU9sv?p=preview). If you could look at my github repo: https://github.com/Hooyek/ERP_frontend that would be nice.
Even when I put my input outside form-group, I don't receive any errors, so it's look like it's not even starting.

Maybe other modules are breaking it? Can you look at it? 
(Look /#/dashboard/users on dev server and then edit to open modal with my form)

**Comment by jonsamwell** [comment]
Try using the latest angular version.
You also haven't go the angular-auto-validate dependency anywhere in your bower file so it might not even be getting loaded by your webpage as it probably can't be found.
https://github.com/Hooyek/ERP_frontend/blob/master/bower.json#L4

On your form you will need the ng-submit directive and on each form control you will need the ng-model directive.

https://github.com/Hooyek/ERP_frontend/blob/master/app/views/pages/login.html#L9
https://github.com/Hooyek/ERP_frontend/blob/master/app/views/form.html#L17

If that is not is my guess is it is probably something to do with the lazy loading stuff you are doing.  I'm sorry but I haven't got the time to look fully into this problem.  I suggest you put a few break points in the library to ensure it is actually getting loaded.

Maybe here:

https://github.com/jonsamwell/angular-auto-validate/blob/master/dist/jcs-auto-validate.js#L1207

Best of luck

**Comment by jonsamwell** [comment]
Working plunker here for your reference http://plnkr.co/edit/R4vGhrSYvKJREMV7Q4rC?p=preview
