### ISSUE TITLE
How to validate form element on focusout of element?

### ISSUE THREAD

**Issue by mihirvadaliaopenxcell** [jonsamwell/angular-auto-validate#80]
Hi jonsamwell,

This is really great plugin and easy to implement. But i can't find one feature like validate form element on focus-out. Can you please tell me is there any way to do it or any plan for future release?

**Comment by jonsamwell** [comment]
Hi! You need to set ng-model-options to update on blur.

https://docs.angularjs.org/api/ng/directive/ngModelOptions

```
<input type="text" name="userName"
             ng-model="user.name"
             ng-model-options="{ updateOn: 'blur' }">
```

**Comment by mihirvadaliaopenxcell** [comment]
Thank you. Actually i am new in angular JS and you solved my problem. Thank you again.

**Comment by bhavesh-vyas** [comment]
Hi,

How to set updateOn : 'blur' by default. at app.run ?

**Comment by jonsamwell** [comment]
http://jonsamwell.com/angularjs-set-default-blur-behaviour-on-ngmodeloptions/
