### ISSUE TITLE
Problem with overriding ngModel and using ngModelOptions in another directive

### ISSUE THREAD

**Issue by MayGo** [jonsamwell/angular-auto-validate#83]
When using angular-material directive mdSelect with  ng-model-options="{trackBy: '$value.code'}" then $options is undefined in mdSelect directive.

codepen: http://codepen.io/MayGo/pen/aOMLEW

In angular-material.js (http://codepen.io/MayGo/pen/yNwzwJ.js)  i log to console:
console.log("There is ngModel.$options when you browse object in chrome developer tools. But not directly ngModel.$options")
console.log(ngModel)
console.log(ngModel.$options)

Is angular-auto-validate ngModel override wrongly implemented or is angular-material using ngModelOptions incorrectly?

**Comment by jonsamwell** [comment]
What version of angular are you using?

**Comment by jonsamwell** [comment]
What is actually going wrong?

**Comment by MayGo** [comment]
angular 1.3.15
tmp.myObj is not displayed in mdSelect because ng-model-options="{trackBy: '$value.code'}" is not working.
I have  debugged the problem, and problem is in 'ngModelDirective' decorator, without it everything works.

**Comment by jonsamwell** [comment]
Do you know what is going wrong in the ngModelDirective decorator?

**Comment by MayGo** [comment]
That i don't know

**Comment by jonsamwell** [comment]
I'll try and debug the plunker later :-)

**Comment by jonsamwell** [comment]
@MayGo I am looking at this now.  First thought is that the track-by in the ng-model-options on the md-select directive is not a valid option (See https://code.angularjs.org/1.3.15/docs/api/ng/directive/ngModelOptions).

ng-model-options="{trackBy: '$value.code'}"

I've taken this out but it still doesn't work.  I'll debug this now.

**Comment by jonsamwell** [comment]
OK ignore my comment above I didn't realise that angular-material allows you to add a track-by value in ngModelOptions.  I have now fixed this issue.  It turned out to be the execution order of the pre and post functions in the ngModelDecorator which has now been fixed.  If you get the latest version it now works (v1.18.11)
