### ISSUE TITLE
ngModelOptions and supportsNgModelOptions logic mistake

### ISSUE THREAD

**Issue by MayGo** [jonsamwell/angular-auto-validate#85]
I think ngModelDirective has logic mistake with using supportsNgModelOptions  in row:
https://github.com/jonsamwell/angular-auto-validate/blob/e12541b17bf7e7ce32e2547a1e8fdd95d445d2eb/src/config/ngModelDecorator.js#L37

There should be NOT supportsNgModelOptions.
if (!supportsNgModelOptions || ngModelOptions === undefined || ngModelOptions.updateOn === undefined || ngModelOptions.updateOn === '')

**Comment by jonsamwell** [comment]
Yep this looks like a mistake.  I'll correct and push a release out

**Comment by jonsamwell** [comment]
Fixed in V1.18.15
