### ISSUE TITLE
support for radio/checkbox groups?

### ISSUE THREAD

**Issue by ericpolkadoc** [jonsamwell/angular-auto-validate#87]
Hi,

This seems to work great for text inputs, but Im having some issues with radio and checkboxes -- does this currently support it?

If so can you please post an example?

Thanks!

**Comment by jonsamwell** [comment]
Fixed in the latest release v1.18.16

Here a plunker to demonstrate

http://plnkr.co/edit/HG0PoiRkEgbv2wCrLxLd?p=preview

**Comment by ericpolkadoc** [comment]
Hi --

So I was close -- and it works great now, however the error message is prepending the last label, in the last radio button.  Here's a snippet, if you could let me know your thoughts that would be great.

If it makes any difference, Im building the list dynamically using ng-repeat.

    <div ng-if="formQuestion.elementType == 'radio'" class="form-group">
        <div ng-repeat="option in formQuestion.options" class="radio">
            <label>
                <input type="radio" name="optionsRadios" id="optionsRadios{{$index}}" ng-model="option.checked" value="option.answerId" required/> {{option.answerText}}
            </label>
         </div>
    </div>

my output in the markup results to this after triggering the required validation.  See the "At Home" label, the error message is appearing before it (5th line from bottom).

    <div ng-if="formQuestion.elementType == 'radio'" class="form-group ng-scope has-error has-feedback">
        
        <div ng-repeat="option in formQuestion.options" class="radio ng-scope">
            <label class="ng-binding">
                <input type="radio" name="optionsRadios" id="optionsRadios0" ng-model="option.checked" value="option.answerId" required="" class="ng-pristine ng-untouched ng-invalid ng-invalid-required"> Pharmacy
            </label>
        </div>
        
        <div ng-repeat="option in formQuestion.options" class="radio ng-scope">
            <label class="ng-binding">
                <input type="radio" name="optionsRadios" id="optionsRadios1" ng-model="option.checked" value="option.answerId" required="" class="ng-pristine ng-untouched ng-invalid ng-invalid-required"> Doctor's Office
            </label>
        </div>
        
        <div ng-repeat="option in formQuestion.options" class="radio ng-scope">
            <label class="ng-binding">
                <input type="radio" name="optionsRadios" id="optionsRadios2" ng-model="option.checked" value="option.answerId" required="" class="ng-pristine ng-untouched ng-invalid ng-invalid-required"><span class="help-block has-error error-msg">This field is required</span> At Home
            </label>
        </div>
        
    </div>
