### ISSUE TITLE
Validator dont work correctly when the input is inside an ng-repeat

### ISSUE THREAD

**Issue by caferrari** [jonsamwell/angular-auto-validate#89]
I have to validate a collection of inputs, but the validator validate "all at once", and shows the message only on the first one... is there a way to prevent this problem?

```
<div class="input-group m-b-md" data-ng-repeat="field in model.fields">
  <input type="text" class="form-control"
    data-ng-model="field.value"
    data-ng-minlength="3"
    required />
  <span class="input-group-btn">
    <button class="btn btn-danger" type="button" data-ng-click="removeField(field)">Remove</button>
  </span>
</div>
```

**Comment by jonsamwell** [comment]
Hi,

I'm doing this exact scenario so I know it is working OK.  I think what is happening is the the structure of your html is not what the BS3 element modifier is expecting.  It is expect every element to be wrapped in a 'form-group' parent element as per the BS3 docs.

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/services/bootstrap3ElementModifier.js#L126

See:
http://getbootstrap.com/css/#forms

```
<div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
```

Try that and see how you get on.

**Comment by jonsamwell** [comment]
I think the html should look something like this in your case

```
<div class="form-group">
    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
      <div class="input-group-addon">.00</div>
    </div>
  </div>
```

**Comment by caferrari** [comment]
Thanks @jonsamwell, that was the problem =) and sry for not figuring it out myself =/

**Comment by jonsamwell** [comment]
No worries!

**Comment by bhavesh-vyas** [comment]
Hi, 

How to deal with such condition,  when we want to show server side validation error msg.?

**Comment by bhavesh-vyas** [comment]
@jonsamwell ,

How to show server side validation errors when input is inside ng-repeat.

**Comment by jonsamwell** [comment]
@bhavesh-vyas I'll try and do an example plunker tomorrow

**Comment by bhavesh-vyas** [comment]
Ok,  thanks!

-Bhavesh

**Comment by bhavesh-vyas** [comment]
Hi @jonsamwell ,

Did you get chance to try?

**Comment by jonsamwell** [comment]
@bhavesh-vyas This shows a very basic example of an async validator and setting external validation.

http://plnkr.co/edit/kjGjBchrXH7LDc7Sa6Kp?p=preview

**Comment by bhavesh-vyas** [comment]
Dear Jon,

Problem is with when we using ng-repeat and serverside validation error occurs then we get that error msg array, the how to point that to the exact field[index] inside ng-repeat
