### ISSUE TITLE
(External) Form Level Validation

### ISSUE THREAD

**Issue by schlegel** [jonsamwell/angular-auto-validate#90]
Hi, 
thanks for the great library!

Is there a way to integrate form level validation as well? For instance I get a server side validation which can't directly be associated with one specific element. E.g. (Username/Password missmatch, Timeout, ...) . The setExternalValidation method only is available on formCtrl children. But I would like to use it directly on the form to show global error messages.

**Comment by jonsamwell** [comment]
Currently no you would have to do some custom code at the point of getting the form level validation message back.  You could make you're own element modifier which has some special logic for this.
