### ISSUE TITLE
<select> or  <input type ='radio'  valid  show page not satisfaction

### ISSUE THREAD

**Issue by yichengjie** [jonsamwell/angular-auto-validate#93]
if my form  contain  radio  or  select ， hava no  good method to show   valid tip  in t
![qq 20150917153814](https://cloud.githubusercontent.com/assets/11714828/9927564/36785f56-5d52-11e5-9786-4e38953732d2.png)
he page

**Comment by jonsamwell** [comment]
Looks like you will just need to set the has-feedback icon the float:right.  If not please do a plunker to reproduce the error.

This works fine

http://plnkr.co/edit/HG0PoiRkEgbv2wCrLxLd?p=preview
