### ISSUE TITLE
Prevent from validating disabled inputs

### ISSUE THREAD

**Issue by qbunia** [jonsamwell/angular-auto-validate#99]
Hello,

I having problem with disabling input from javascript and then validating it. I have checkbox that if its checked the input that is required is disabled. The problem is that before I check the checkbox I type something in input that is invalid, then I check checkbox and the disabled input is still in invalid state, even if I submit my form. Is there anything Iam doing wrong or maybe angular-auto-validate does not have this kind of functionality?

**Comment by jonsamwell** [comment]
Hi @qbunia,

The library does not have this functionality out of the box however it can be acheived by reseting the controls state using the validation manager.  Once the required flag changes to false you will have to call the resetElement method on the validation manager passing in the element.

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/services/validationManager.js#L123

Similiar functionality can be seen in the reset form direcitve

https://github.com/jonsamwell/angular-auto-validate/blob/master/src/directives/formReset.js#L8

Thanks,

Jon
